
CREATE DATABASE GerenciamentoPatrimonioDB
GO

USE GerenciamentoPatrimonioDB
GO

CREATE TABLE Cidade(
CidadeID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeCidade VARCHAR(100) NOT NULL,
Estado VARCHAR(50) NOT NULL
)
GO

CREATE TABLE Bairro(
BairroID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeBairro VARCHAR(50) NOT NULL,

CidadeID UNIQUEIDENTIFIER NOT NULL,

CONSTRAINT Fk_CidadeID FOREIGN KEY (CidadeID) REFERENCES Cidade(CidadeID) ON DELETE CASCADE,
)
GO

CREATE TABLE Endereco(
EnderecoID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Lougradoura VARCHAR(100) NOT NULL,
Complemento VARCHAR(50),
CEP VARCHAR(9) NOT NULL,

BairroID UNIQUEIDENTIFIER NOT NULL,

CONSTRAINT Fk_Bairro FOREIGN KEY (BairroID) REFERENCES Bairro(BairroID)
)
GO

CREATE TABLE Area(
AreaID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeArea VARCHAR(50) NOT NULL
)
GO

CREATE TABLE Cargo(
CargoID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeCargo VARCHAR(50) NOT NULL
)
GO

CREATE TABLE LocalAmbiente(
LocalAmbienteID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Nome VARCHAR(100),
LocalSAP INT, 
DescricaoSAP VARCHAR(100),

AreaID UNIQUEIDENTIFIER,

CONSTRAINT Fk_Area FOREIGN KEY (AreaID) REFERENCES Area(AreaID) ON DELETE CASCADE
)
GO

CREATE TABLE StatusPatrimonio(
StatusPatrimonioID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeTipo VARCHAR(50) NOT NULL UNIQUE
)
GO

CREATE TABLE StatusTransferencia(
StatusTransferenciaID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeTipo VARCHAR(50) NOT NULL
)
GO	

CREATE TABLE TipoPatrimonio(
TipoPatrimonioID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeTipo VARCHAR(50)
)
GO

CREATE TABLE Patrimonio(
PatrimonioID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NumeroSerie	VARCHAR(30),

EnderecoID UNIQUEIDENTIFIER NOT NULL,
TipoPatrimonioID UNIQUEIDENTIFIER,
StatusPatrimonioID UNIQUEIDENTIFIER NOT NULL,

CONSTRAINT Fk_Endereco FOREIGN KEY (EnderecoID) REFERENCES Endereco(EnderecoID) ON DELETE CASCADE,
CONSTRAINT Fk_TipoPatrimonio FOREIGN KEY (TipoPatrimonioID) REFERENCES TipoPatrimonio(TipoPatrimonioID) ON DELETE CASCADE,
CONSTRAINT Fk_StatusPatrimonio FOREIGN KEY (StatusPatrimonioID) REFERENCES StatusPatrimonio(StatusPatrimonioID) ON DELETE CASCADE
)
GO

CREATE TABLE TipoUsuario(
TipoUsuarioID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeTipo VARCHAR(50)
)
GO

CREATE TABLE Usuario(
UsuarioID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Nome NVARCHAR(100),
RG VARCHAR(15),
CPF VARCHAR(11),
CarteiraTrabalho VARCHAR(14),
Senha VARBINARY(32),	
Email VARCHAR(150),

EnderecoID UNIQUEIDENTIFIER NOT NULL,
CargoID UNIQUEIDENTIFIER NOT NULL,
TipoUsuarioID UNIQUEIDENTIFIER NOT NULL,

CONSTRAINT Fk_EnderecoUsuario FOREIGN KEY (EnderecoID) REFERENCES Endereco(EnderecoID) ON DELETE CASCADE,
CONSTRAINT Fk_Cargo FOREIGN KEY (CargoID) REFERENCES Cargo(CargoID) ON DELETE CASCADE,
CONSTRAINT Fk_TipoUsuario FOREIGN KEY (TipoUsuarioID) REFERENCES TipoUsuario(TipoUsuarioID) ON DELETE CASCADE
)
GO

CREATE TABLE SolicitacaoTransferencia(
SolicitacaoTransferencia UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
DataCriacaoSolicicao DATETIME2(0) NOT NULL, 
DataReposta DATETIME2(0) NOT NULL,
Justificativa NVARCHAR(MAX), 

StatusTransferenciaID UNIQUEIDENTIFIER,
UsuarioIDSoliciatacao UNIQUEIDENTIFIER,
UsuarioIDTransferencia UNIQUEIDENTIFIER,
PatrimonioID UNIQUEIDENTIFIER,
LocalAmbienteID UNIQUEIDENTIFIER,

CONSTRAINT Fk_Status FOREIGN KEY (StatusTransferenciaID) REFERENCES StatusTransferencia(StatusTransferenciaID) ON DELETE CASCADE,
CONSTRAINT Fk_UsuarioSoliciatacao FOREIGN KEY (UsuarioIDSoliciatacao) REFERENCES Usuario(UsuarioID),
CONSTRAINT Fk_UsuarioTransferencia FOREIGN KEY (UsuarioIDTransferencia) REFERENCES Usuario(UsuarioID),
CONSTRAINT Fk_Patrimonio FOREIGN KEY (PatrimonioID) REFERENCES Patrimonio(PatrimonioID),
CONSTRAINT Fk_LocalAmbiente FOREIGN KEY (LocalAmbienteID) REFERENCES LocalAmbiente(LocalAmbienteID) ON DELETE CASCADE
)
GO

CREATE TABLE LogPatrimonio(
LogPatrimonioID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
DataTransferencia DATETIME2(0),
TipoAlteracao VARBINARY(20),

StatusPatrimonioID UNIQUEIDENTIFIER,
PatrimonioID UNIQUEIDENTIFIER,
UsuarioID UNIQUEIDENTIFIER,
LocalAmbienteID UNIQUEIDENTIFIER,

CONSTRAINT Fk_StatusPatrimonioLog FOREIGN KEY (StatusPatrimonioID) REFERENCES StatusPatrimonio(StatusPatrimonioID),
CONSTRAINT Fk_PatrimonioLog FOREIGN KEY (PatrimonioID) REFERENCES Patrimonio(PatrimonioID) ON DELETE CASCADE,
CONSTRAINT Fk_UsuarioLog FOREIGN KEY (UsuarioID) REFERENCES Usuario(UsuarioID),
CONSTRAINT Fk_LocalAmbienteLog FOREIGN KEY (LocalAmbienteID) REFERENCES LocalAmbiente(LocalAmbienteID)
)
GO

CREATE TABLE LocalUsuario(
UsuarioID UNIQUEIDENTIFIER,
LocalAmbienteID UNIQUEIDENTIFIER,

CONSTRAINT Pk_LocalUsuario PRIMARY KEY (UsuarioID,LocalAmbienteID),
CONSTRAINT Fk_Local FOREIGN KEY (LocalAmbienteID) REFERENCES LocalAmbiente(LocalAmbienteID) ON DELETE CASCADE,
CONSTRAINT Fk_Usuario FOREIGN KEY (UsuarioID) REFERENCES Usuario(UsuarioID) ON DELETE CASCADE
)
GO